//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Ufba.vShome
{
	/// <summary>
	/// DomainModel vShomeDomainModel
	/// Description for Ufba.vShome.vShome
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.vShome.vShomeDomainModel.DisplayName", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.vShome.vShomeDomainModel.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("632997e7-902d-4f18-9eb8-09de18bf817e")]
	public partial class vShomeDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// vShomeDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x632997e7, 0x902d, 0x4f18, 0x9e, 0xb8, 0x09, 0xde, 0x18, 0xbf, 0x81, 0x7e);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public vShomeDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(ModelRoot),
				typeof(Feature),
				typeof(Comment),
				typeof(Device),
				typeof(ModelRootHasComments),
				typeof(FeatureReferencesActuator),
				typeof(FeatureReferencesFather),
				typeof(ModelRootHasFeatures),
				typeof(ModelRootHasDevices),
				typeof(FeatureReferencesSensor),
				typeof(FeatureReferencesBrother),
				typeof(FeatureReferencesAlternatives),
				typeof(CommentReferencesFeatures),
				typeof(vShomeDiagram),
				typeof(ActuatorConnector),
				typeof(Father),
				typeof(Brother),
				typeof(Alternative),
				typeof(Sensor),
				typeof(CommentLink),
				typeof(CommentBoxShape),
				typeof(FeatureShape),
				typeof(DeviceShape),
				typeof(global::Ufba.vShome.FixUpDiagram),
				typeof(global::Ufba.vShome.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(ModelRoot), "Name", ModelRoot.NameDomainPropertyId, typeof(ModelRoot.NamePropertyHandler)),
				new DomainMemberInfo(typeof(ModelRoot), "Port", ModelRoot.PortDomainPropertyId, typeof(ModelRoot.PortPropertyHandler)),
				new DomainMemberInfo(typeof(Feature), "FeatureType", Feature.FeatureTypeDomainPropertyId, typeof(Feature.FeatureTypePropertyHandler)),
				new DomainMemberInfo(typeof(Feature), "Serial", Feature.SerialDomainPropertyId, typeof(Feature.SerialPropertyHandler)),
				new DomainMemberInfo(typeof(Feature), "FeatureName", Feature.FeatureNameDomainPropertyId, typeof(Feature.FeatureNamePropertyHandler)),
				new DomainMemberInfo(typeof(Comment), "Text", Comment.TextDomainPropertyId, typeof(Comment.TextPropertyHandler)),
				new DomainMemberInfo(typeof(Device), "Name", Device.NameDomainPropertyId, typeof(Device.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Device), "ReturnType", Device.ReturnTypeDomainPropertyId, typeof(Device.ReturnTypePropertyHandler)),
				new DomainMemberInfo(typeof(Device), "DeviceType", Device.DeviceTypeDomainPropertyId, typeof(Device.DeviceTypePropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(ModelRootHasComments), "ModelRoot", ModelRootHasComments.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasComments), "Comment", ModelRootHasComments.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesActuator), "Feature", FeatureReferencesActuator.FeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesActuator), "Device", FeatureReferencesActuator.DeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesFather), "SourceFeature", FeatureReferencesFather.SourceFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesFather), "TargetFeature", FeatureReferencesFather.TargetFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasFeatures), "ModelRoot", ModelRootHasFeatures.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasFeatures), "Feature", ModelRootHasFeatures.FeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasDevices), "ModelRoot", ModelRootHasDevices.ModelRootDomainRoleId),
				new DomainRolePlayerInfo(typeof(ModelRootHasDevices), "Device", ModelRootHasDevices.DeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesSensor), "Feature", FeatureReferencesSensor.FeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesSensor), "Device", FeatureReferencesSensor.DeviceDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesBrother), "SourceFeature", FeatureReferencesBrother.SourceFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesBrother), "TargetFeature", FeatureReferencesBrother.TargetFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesAlternatives), "SourceFeature", FeatureReferencesAlternatives.SourceFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(FeatureReferencesAlternatives), "TargetFeature", FeatureReferencesAlternatives.TargetFeatureDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferencesFeatures), "Comment", CommentReferencesFeatures.CommentDomainRoleId),
				new DomainRolePlayerInfo(typeof(CommentReferencesFeatures), "Feature", CommentReferencesFeatures.FeatureDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(14);
				createElementMap.Add(typeof(ModelRoot), 0);
				createElementMap.Add(typeof(Feature), 1);
				createElementMap.Add(typeof(Comment), 2);
				createElementMap.Add(typeof(Device), 3);
				createElementMap.Add(typeof(vShomeDiagram), 4);
				createElementMap.Add(typeof(ActuatorConnector), 5);
				createElementMap.Add(typeof(Father), 6);
				createElementMap.Add(typeof(Brother), 7);
				createElementMap.Add(typeof(Alternative), 8);
				createElementMap.Add(typeof(Sensor), 9);
				createElementMap.Add(typeof(CommentLink), 10);
				createElementMap.Add(typeof(CommentBoxShape), 11);
				createElementMap.Add(typeof(FeatureShape), 12);
				createElementMap.Add(typeof(DeviceShape), 13);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Ufba.vShome.vShomeDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new ModelRoot(partition, propertyAssignments);
				case 1: return new Feature(partition, propertyAssignments);
				case 2: return new Comment(partition, propertyAssignments);
				case 3: return new Device(partition, propertyAssignments);
				case 4: return new vShomeDiagram(partition, propertyAssignments);
				case 5: return new ActuatorConnector(partition, propertyAssignments);
				case 6: return new Father(partition, propertyAssignments);
				case 7: return new Brother(partition, propertyAssignments);
				case 8: return new Alternative(partition, propertyAssignments);
				case 9: return new Sensor(partition, propertyAssignments);
				case 10: return new CommentLink(partition, propertyAssignments);
				case 11: return new CommentBoxShape(partition, propertyAssignments);
				case 12: return new FeatureShape(partition, propertyAssignments);
				case 13: return new DeviceShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(9);
				createElementLinkMap.Add(typeof(ModelRootHasComments), 0);
				createElementLinkMap.Add(typeof(FeatureReferencesActuator), 1);
				createElementLinkMap.Add(typeof(FeatureReferencesFather), 2);
				createElementLinkMap.Add(typeof(ModelRootHasFeatures), 3);
				createElementLinkMap.Add(typeof(ModelRootHasDevices), 4);
				createElementLinkMap.Add(typeof(FeatureReferencesSensor), 5);
				createElementLinkMap.Add(typeof(FeatureReferencesBrother), 6);
				createElementLinkMap.Add(typeof(FeatureReferencesAlternatives), 7);
				createElementLinkMap.Add(typeof(CommentReferencesFeatures), 8);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Ufba.vShome.vShomeDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new ModelRootHasComments(partition, roleAssignments, propertyAssignments);
				case 1: return new FeatureReferencesActuator(partition, roleAssignments, propertyAssignments);
				case 2: return new FeatureReferencesFather(partition, roleAssignments, propertyAssignments);
				case 3: return new ModelRootHasFeatures(partition, roleAssignments, propertyAssignments);
				case 4: return new ModelRootHasDevices(partition, roleAssignments, propertyAssignments);
				case 5: return new FeatureReferencesSensor(partition, roleAssignments, propertyAssignments);
				case 6: return new FeatureReferencesBrother(partition, roleAssignments, propertyAssignments);
				case 7: return new FeatureReferencesAlternatives(partition, roleAssignments, propertyAssignments);
				case 8: return new CommentReferencesFeatures(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Ufba.vShome.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return vShomeDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (vShomeDomainModel.resourceManager == null)
				{
					vShomeDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(vShomeDomainModel).Assembly);
				}
				return vShomeDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return vShomeDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return vShomeDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (vShomeDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new vShomeCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					vShomeDomainModel.copyClosure = copyFilter;
				}
				return vShomeDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (vShomeDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new vShomeDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					vShomeDomainModel.removeClosure = removeFilter;
				}
				return vShomeDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Ufba.vShome.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Ufba.vShome.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Ufba.vShome.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Ufba.vShome.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class vShomeDeleteClosure : vShomeDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public vShomeDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class vShomeDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public vShomeDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Ufba.vShome.ModelRootHasComments.CommentDomainRoleId, true);
			DomainRoles.Add(global::Ufba.vShome.ModelRootHasFeatures.FeatureDomainRoleId, true);
			DomainRoles.Add(global::Ufba.vShome.ModelRootHasDevices.DeviceDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class vShomeCopyClosure : vShomeCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public vShomeCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class vShomeCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public vShomeCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: AccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AccessModifier
	{
		/// <summary>
		/// Public
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/Public.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Public = 0,
		/// <summary>
		/// Assembly
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/Assembly.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Assembly = 1,
		/// <summary>
		/// Private
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/Private.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Private = 2,
		/// <summary>
		/// Family
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/Family.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Family = 3,
		/// <summary>
		/// FamilyOrAssembly
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/FamilyOrAssembly.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		FamilyOrAssembly = 4,
		/// <summary>
		/// FamilyAndAssembly
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.AccessModifier/FamilyAndAssembly.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		FamilyAndAssembly = 5,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: TypeAccessModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TypeAccessModifier
	{
		/// <summary>
		/// Public
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.TypeAccessModifier/Public.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Public = 0,
		/// <summary>
		/// Private
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.TypeAccessModifier/Private.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Private = 1,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: InheritanceModifier
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum InheritanceModifier
	{
		/// <summary>
		/// None
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.InheritanceModifier/None.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		None = 0,
		/// <summary>
		/// Abstract
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.InheritanceModifier/Abstract.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Abstract = 1,
		/// <summary>
		/// Sealed
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.InheritanceModifier/Sealed.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Sealed = 2,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: Multiplicity
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Multiplicity
	{
		/// <summary>
		/// ZeroMany
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.Multiplicity/ZeroMany.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		ZeroMany = 0,
		/// <summary>
		/// One
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.Multiplicity/One.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		One = 1,
		/// <summary>
		/// ZeroOne
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.Multiplicity/ZeroOne.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		ZeroOne = 2,
		/// <summary>
		/// OneMany
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.Multiplicity/OneMany.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		OneMany = 3,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: OperationConcurrency
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum OperationConcurrency
	{
		/// <summary>
		/// Sequential
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.OperationConcurrency/Sequential.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Sequential = 0,
		/// <summary>
		/// Guarded
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.OperationConcurrency/Guarded.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Guarded = 1,
		/// <summary>
		/// Concurrent
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.OperationConcurrency/Concurrent.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Concurrent = 2,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: ReturnType
	/// Description for Ufba.vShome.ReturnType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum ReturnType
	{
		/// <summary>
		/// BOOL
		/// Description for Ufba.vShome.ReturnType.BOOL
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.ReturnType/BOOL.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		BOOL,
		/// <summary>
		/// INFO
		/// Description for Ufba.vShome.ReturnType.INFO
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.ReturnType/INFO.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		INFO,
		/// <summary>
		/// RANGE
		/// Description for Ufba.vShome.ReturnType.RANGE
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.ReturnType/RANGE.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		RANGE,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: FeatureName
	/// Description for Ufba.vShome.FeatureName
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FeatureName
	{
		/// <summary>
		/// UserAirConditionerControl
		/// Description for Ufba.vShome.FeatureName.UserAirConditionerControl
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/UserAirConditionerControl.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		UserAirConditionerControl,
		/// <summary>
		/// UserIlumination
		/// Description for Ufba.vShome.FeatureName.UserIlumination
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/UserIlumination.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		UserIlumination,
		/// <summary>
		/// AutomatedIluminationByLuminosity
		/// Description for Ufba.vShome.FeatureName.AutomatedIluminationByLuminosity
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/AutomatedIluminationByLuminosity.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		AutomatedIluminationByLuminosity,
		/// <summary>
		/// AutomatedWindowControl
		/// Description for Ufba.vShome.FeatureName.AutomatedWindowControl
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/AutomatedWindowControl.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		AutomatedWindowControl,
		/// <summary>
		/// AutomatedIluminationByPresence
		/// Description for Ufba.vShome.FeatureName.AutomatedIluminationByPresence
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/AutomatedIluminationByPresence.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		AutomatedIluminationByPresence,
		/// <summary>
		/// PresenceIlusion
		/// Description for Ufba.vShome.FeatureName.PresenceIlusion
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/PresenceIlusion.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		PresenceIlusion,
		/// <summary>
		/// AutomatedAirConditionerControl
		/// Description for Ufba.vShome.FeatureName.AutomatedAirConditionerControl
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/AutomatedAirConditionerControl.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		AutomatedAirConditionerControl,
		/// <summary>
		/// UserWindowControl
		/// Description for Ufba.vShome.FeatureName.UserWindowControl
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/UserWindowControl.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		UserWindowControl,
		/// <summary>
		/// PanicMode
		/// Description for Ufba.vShome.FeatureName.PanicMode
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/PanicMode.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		PanicMode,
		/// <summary>
		/// AlarmAgainstRobbery
		/// Description for Ufba.vShome.FeatureName.AlarmAgainstRobbery
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/AlarmAgainstRobbery.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		AlarmAgainstRobbery,
		/// <summary>
		/// LockDoors
		/// Description for Ufba.vShome.FeatureName.LockDoors
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureName/LockDoors.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		LockDoors,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: DeviceType
	/// Description for Ufba.vShome.DeviceType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum DeviceType
	{
		/// <summary>
		/// Actuator
		/// Description for Ufba.vShome.DeviceType.Actuator
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.DeviceType/Actuator.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Actuator,
		/// <summary>
		/// Sensor
		/// Description for Ufba.vShome.DeviceType.Sensor
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.DeviceType/Sensor.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Sensor,
	}
}
namespace Ufba.vShome
{
	/// <summary>
	/// DomainEnumeration: FeatureType
	/// Description for Ufba.vShome.FeatureType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FeatureType
	{
		/// <summary>
		/// OR
		/// Description for Ufba.vShome.FeatureType.OR
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureType/OR.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		OR,
		/// <summary>
		/// Mandatory
		/// Description for Ufba.vShome.FeatureType.Mandatory
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureType/Mandatory.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Mandatory,
		/// <summary>
		/// Alternative
		/// Description for Ufba.vShome.FeatureType.Alternative
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureType/Alternative.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Alternative,
		/// <summary>
		/// Optional
		/// Description for Ufba.vShome.FeatureType.Optional
		/// </summary>
		[DslDesign::DescriptionResource("Ufba.vShome.FeatureType/Optional.Description", typeof(global::Ufba.vShome.vShomeDomainModel), "Ufba.vShome.GeneratedCode.DomainModelResx")]
		Optional,
	}
}

