//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ufba.vShome
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "visSHome";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"vShome";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Ufba";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID vShomeDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(vShomeCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID vShomeExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(vShomeCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewvShomeExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(vShomeCommandSetId), 0x0001);
	
		// Package identifier
		public const string vShomePackageId = "c52771ae-c860-4014-befb-d1c7766f19f9";
		
		// Editor factory identifier
		public const string vShomeEditorFactoryId = "4ec00923-c29b-496a-ac39-4c8aec7fce8d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string vShomeModelExplorerToolWindowId = "458b7ea5-ccdb-4c4a-a3b6-42292eb1c295";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Ufba.vShome
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string vShomeCommandSetId = "45762e95-252b-4ec3-94e4-c38ae530b2fc";
	}
}